version: '3'
services:
  db:
    image: mysql:5.7
    container_name: '${MYSQL_HOST}'
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'

  # hackthon-web-app:
  #   build: .
  #   image: hackthon/winners
  #   container_name: hack
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"